### ISSUE TITLE
Ошибка связанная со строкой

### ISSUE THREAD

**Issue by infinitysc** [infinitysc/Invertor#5]
time: 1731320360238
msg: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.build.Invertor/com.build.Invertor.mainModule.SingleActivity.MainActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3955)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8282)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:1014)
	at com.build.Invertor.model.json.JsonDownloader.<init>(JsonDownloader.kt:40)
	at com.build.Invertor.model.Model$Checker.getModel(Model.kt:212)
	at com.build.Invertor.mainModule.SingleActivity.MainActivity.onCreate(MainActivity.kt:19)
	at android.app.Activity.performCreate(Activity.java:8636)
	at android.app.Activity.performCreate(Activity.java:8614)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1466)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3796)
	... 12 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:358)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 22 more

**Comment by infinitysc** [comment]
Убрал создание model в activity 
Ошибка связана с тем что вход получает не массив объектов а строку
Чуть позже добавлю обработчик случая если вылазет JsonSyntaxException
